services:
  npm-autodiscovery:
    image: raddadengineer/npm-autodiscovery:latest
    container_name: npm-autodiscovery
    restart: unless-stopped
    ports:
      - '${PORT:-8080}:${PORT:-8080}'
    env_file:
      - .env
    volumes:
      # Read-only Docker socket mapping
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - npm-network

networks:
  npm-network:
    name: ${NPM_NETWORK:-npm-network}
    external: true
