package upstream

import (
	"fmt"
	"regexp"
	"strings"
)

var sanitizeRegex = regexp.MustCompile(`[^a-zA-Z0-9_]`)

// Server represents an individual replica upstream target.
type Server struct {
	Target      string // e.g. "172.20.0.12:8080"
	MaxFails    int    // default 3
	FailTimeout string // default "10s"
}

// Config represents the upstream definition for scaled service load balancing.
type Config struct {
	Domain      string
	Path        string
	Name        string   // Optional override, default upstream_<sanitized_domain>
	Algorithm   string   // "least_conn" (default), "round_robin", "ip_hash"
	Servers     []Server
}

// SanitizeUpstreamName converts a domain and optional subpath into a valid Nginx upstream identifier.
func SanitizeUpstreamName(domain, path string) string {
	combined := domain
	cleanPath := strings.Trim(path, "/")
	if cleanPath != "" {
		combined += "_" + cleanPath
	}
	sanitized := sanitizeRegex.ReplaceAllString(combined, "_")
	sanitized = strings.Trim(sanitized, "_")
	for strings.Contains(sanitized, "__") {
		sanitized = strings.ReplaceAll(sanitized, "__", "_")
	}
	return "upstream_" + sanitized
}

// GenerateUpstreamBlock synthesizes an Nginx upstream directive block.
func GenerateUpstreamBlock(cfg Config) string {
	if len(cfg.Servers) == 0 {
		return ""
	}

	name := cfg.Name
	if name == "" {
		name = SanitizeUpstreamName(cfg.Domain, cfg.Path)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Auto-generated by NPM-AutoDiscovery for domain: %s\n", cfg.Domain))
	sb.WriteString(fmt.Sprintf("upstream %s {\n", name))

	// Load balancing algorithm directive
	algo := strings.ToLower(strings.TrimSpace(cfg.Algorithm))
	switch algo {
	case "ip_hash", "ip-hash":
		sb.WriteString("    ip_hash;\n")
	case "round_robin", "round-robin", "roundrobin":
		// Nginx default is round-robin
	case "least_conn", "least-conn", "":
		sb.WriteString("    least_conn;\n")
	default:
		sb.WriteString("    least_conn;\n")
	}

	for _, s := range cfg.Servers {
		maxFails := s.MaxFails
		if maxFails <= 0 {
			maxFails = 3
		}
		failTimeout := s.FailTimeout
		if failTimeout == "" {
			failTimeout = "10s"
		}
		sb.WriteString(fmt.Sprintf("    server %s max_fails=%d fail_timeout=%s;\n", s.Target, maxFails, failTimeout))
	}

	sb.WriteString("}")
	return sb.String()
}
