package upstream

import (
	"strings"
	"testing"
)

func TestSanitizeUpstreamName(t *testing.T) {
	tests := []struct {
		domain string
		path   string
		want   string
	}{
		{"api.company.com", "", "upstream_api_company_com"},
		{"app.example.com", "/api", "upstream_app_example_com_api"},
		{"sub.domain.local:8080", "/v1/auth", "upstream_sub_domain_local_8080_v1_auth"},
	}

	for _, tt := range tests {
		got := SanitizeUpstreamName(tt.domain, tt.path)
		if got != tt.want {
			t.Errorf("SanitizeUpstreamName(%q, %q) = %q, want %q", tt.domain, tt.path, got, tt.want)
		}
	}
}

func TestGenerateUpstreamBlock(t *testing.T) {
	cfg := Config{
		Domain:    "api.company.com",
		Algorithm: "least_conn",
		Servers: []Server{
			{Target: "172.20.0.12:8080", MaxFails: 3, FailTimeout: "10s"},
			{Target: "172.20.0.13:8080", MaxFails: 3, FailTimeout: "10s"},
			{Target: "172.20.0.14:8080", MaxFails: 3, FailTimeout: "10s"},
		},
	}

	block := GenerateUpstreamBlock(cfg)

	expectedLines := []string{
		"# Auto-generated by NPM-AutoDiscovery for domain: api.company.com",
		"upstream upstream_api_company_com {",
		"    least_conn;",
		"    server 172.20.0.12:8080 max_fails=3 fail_timeout=10s;",
		"    server 172.20.0.13:8080 max_fails=3 fail_timeout=10s;",
		"    server 172.20.0.14:8080 max_fails=3 fail_timeout=10s;",
		"}",
	}

	for _, l := range expectedLines {
		if !strings.Contains(block, l) {
			t.Errorf("GenerateUpstreamBlock missing expected line: %s\nGot:\n%s", l, block)
		}
	}
}

func TestGenerateUpstreamBlockIPHash(t *testing.T) {
	cfg := Config{
		Domain:    "auth.company.com",
		Algorithm: "ip_hash",
		Servers: []Server{
			{Target: "10.0.0.5:8000"},
			{Target: "10.0.0.6:8000"},
		},
	}

	block := GenerateUpstreamBlock(cfg)
	if !strings.Contains(block, "ip_hash;") {
		t.Errorf("expected ip_hash directive in block:\n%s", block)
	}
	if !strings.Contains(block, "server 10.0.0.5:8000 max_fails=3 fail_timeout=10s;") {
		t.Errorf("expected default max_fails and fail_timeout in block:\n%s", block)
	}
}
